# Public configuration; no runtime token or private key is stored here.
apiVersion: v1
kind: Secret
metadata:
  name: cluster-tokyo-gke
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: tokyo-gke
  server: https://34.146.143.116
  namespaces: sample-app
  clusterResources: 'false'
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": [
          "gcp"
        ],
        "apiVersion": "client.authentication.k8s.io/v1beta1",
        "env": {
          "GOOGLE_APPLICATION_CREDENTIALS": "/etc/crystal-gcp-wif/credential-configuration.json"
        }
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU40Zk9OMG1YQlJsNFg5eXBpalBiaDB3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa056UXhOakE1WldNdE1URTJZUzAwTVRFNUxXSmhNekF0T0RFM1pURTRPRGRrWldNNApNQ0FYRFRJMk1UQXdPVEE1TURRd05sb1lEekl3TlRZeE1EQXhNVEF3TkRBMldqQXZNUzB3S3dZRFZRUURFeVEzCk5ERTJNRGxsWXkweE1UWmhMVFF4TVRrdFltRXpNQzA0TVRkbE1UZzROMlJsWXpnd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDWE9uT1RWUmY3bmNyN1ZmZVlUUkRDWEU5S3N3b3RuTmFpZ3laWgpnTDJiMmlBLzR2NGpCM1dUbzJlaTBVWWlSVndyWVl4bXFpTjZBWkp2Q29tOVl3UFlBTDVNSFRMZkZaeTE2Y0FHCkpUQ01sT3VxOFVtSk92Y0IwN0Q1WGdrWWdmQkMvSXdGazNWdnpITkV1R0pyTUZraFNCYXUrMU9rSnhkeTFwQkEKVnBacGc3QUdTNU5mNklqK2syYjE5ZFFqazFaRml5Y3RRM05LOFAwdTNjVWgvQkhWWlRzTDNjdDBscFBPRzJJdwp5S1dQcEJZYnlWZjFsQTdDUC9qL1psdVQvd3ozUlh6N1lvNTVwdkxydWFnWWYwQ0hhVi8rbmVKMkhoMk00akdnCnpiVktTME1EVmNDVVhvZG5wV3JVWk50eGo3ekk3eS9RSkFldys4dVVpcXVmNmpjRkkyZWJ2M2VFcjJEMFUzNkYKR3BUK25RUzcxV1ZZeExvY1pyTG5HU0c1VDFxaVdOeENMdzN1KzNRbkVFdll6U3RmTEJiemI1R0tYOGwzb3dZdgpxZzFoVGJiaWUxQjlnc09ORTIyMW5UVngxWlVUanZVSkcwWmpGRmZvZUROQk0yTTFsZ2RMbjV0N3VHTk1RNjNKCi9mTEVDOEp4SEdmYzFUSXBRZ3J6eDJOcUU0c0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSkVIeFJaeFdSTXBYOGVkLzNYRldKNWNBVU5mTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQmcyQ2lBNC95WnJQVE02dGQwaThqdjFhZmZNajZFc0ZkZEZ5YzBqZ3BECldiTlpQRFV3azZKcVRVSDNFVWxoT2RrUFFQRU90TnhvY2tXdmt4QU43Sk9HcGFrTUNCWkFmNHZuVzdNQjNvamsKQjIzTmwwQkhjVGpycmFleS9HZndSbkdCT1hKeFVLVnBUazJXWXd0MnM0d0VNMTU2MkI3UVlWZ3BpSWVvd0VDSQp6cXlHSjVtUkRSaXVxcDFhaXB6Q3FhL0Z1WU9pd3lsbm5uQ1FLMnk4K2JobmlHdlVTUFcrQXdXKzQ5THdBQm01CmE1emNnWkJlK2l5TlBtKzRSMUh4aTEyM3VjcWxGcGV2VHNieEFWUnNQd3FnSzJsOGZQODZLUStvNkZqd01QeFoKMTZ3b04yeXNuVTVnZDJBNEtRSmNSaEJEcWZ5WTBqN0h5MERwV3huUmRYQlMzT1I2VVByV3dVWWx4eVF3NE9VRQpmeVlkVUhzdDFsOGhqS2dmU1Fya0NXWU85OXdDYUN0RDBicVdyTGxkZTljaDZkN3hmUCtjdGV4L2tYaUp5MldHCnRKaTlDV0oycnBtUEt5YmVRMGVwdXR3TjdrcEVWUWVzQngySWIvbmUwdk5BNGVyTTk5b3JGdFl0Sm9sdWVKNm8KRFd1dG5IRTJZWmIrcXdZVDRSNXBIZDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
