apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    app.kubernetes.io/part-of: crystal-gke-bootstrap
---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    app.kubernetes.io/part-of: crystal-gke-bootstrap
